apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pet-consumer
  template:
    metadata:
      labels:
        app: pet-consumer
    spec:
      containers:
      - name: pet-backend-container
        image: tapiwanashembizvo/pet-consumer:nano
        ports:
        - containerPort: 8789
        env:
        - name:  CONFIG_SERVER_URL
          valueFrom:
            secretKeyRef:
              name:  pet-app-secret
              key:  CONFIG_SERVER_URL
        resources:
          requests:
            memory: "50Mi" #memory is messured in Mi and Gi 
            cpu: "150m" #1000m  = 1 cpu core 
          
          limits:
            memory: "200Mi"
            cpu: "500m"
      
    
