apiVersion: v1
kind: Secret
metadata:
  name: postgres-db-secret
type: Opaque
data:
  DB_URL: amRiYzpwb3N0Z3Jlc3FsOi8vMTAuMC4wLjEwMjo1NDMy  # base64-encoded value
  DB_USER: YWRtaW4=
  DB_PASS: YWRtaW4=