apiVersion: apps/v1
kind: Deployment
metadata:
  name: nice-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nice-app
  template:
    metadata:
      labels:
        app: nice-app
    spec:
      containers:
      - name: nice-app-container
        image: tapiwanashembizvo/nice-app-img:1.0
        ports:
        - containerPort: 8778
