apiVersion: v1
kind: Service
metadata:
  name: nice-app-service
spec:
  type: NodePort
  selector:
    app: nice-app
  ports:
    - protocol: TCP
      port: 8778
      targetPort: 8778
      nodePort: 30904
