apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"nice-app","namespace":"dev-namespace"},"spec":{"replicas":3,"selector":{"matchLabels":{"app":"nice-app"}},"template":{"metadata":{"labels":{"app":"nice-app"}},"spec":{"containers":[{"image":"tapiwanashembizvo/nice-app-img:1.0","name":"nice-app-container","ports":[{"containerPort":8778}]}]}}}}
  creationTimestamp: "2024-09-30T17:59:20Z"
  generation: 4
  name: nice-app
  namespace: dev-namespace
  resourceVersion: "213062"
  uid: 95627297-f7aa-4f8f-ad32-98154b1d2495
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nice-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nice-app
    spec:
      containers:
      - image: tapiwanashembizvo/nice-app:18
        imagePullPolicy: IfNotPresent
        name: nice-app-container
        ports:
        - containerPort: 8778
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2024-09-30T17:59:22Z"
    lastUpdateTime: "2024-09-30T17:59:22Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-09-30T17:59:20Z"
    lastUpdateTime: "2024-10-01T08:19:05Z"
    message: ReplicaSet "nice-app-5d79c64766" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 4
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
