apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"  # This makes it the default storage class
provisioner: kubernetes.io/no-provisioner  # Since hostPath does not support dynamic provisioning
volumeBindingMode: WaitForFirstConsumer
