version: '3.8'

services:
  db:
    image: postgres:15-alpine3.19
    container_name: postgres_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    secrets:
      - db_user
      - db_password
    networks:
      - postgres-network

volumes:
  pgdata:

secrets:
  db_user:
    file: /home/developer/dev/env/db_user.txt
  db_password:
    file: /home/developer/dev/env/db_password.txt

networks:
  postgres-network: